#!/usr/bin/env ruby
source ENV['GEM_SOURCE'] || 'https://rubygems.org'

group :test do
  gem 'rake',                           :require => false unless dependencies.map(&:name).include?('rake')
  gem 'rspec-puppet',                   :require => false
  gem 'rspec-its',                      :require => false
  gem 'puppetlabs_spec_helper',         :require => false
  gem 'puppet-lint',                    :require => false
  gem 'metadata-json-lint',             :require => false
  gem 'os',                             :require => false
  gem 'simplecov',                      :require => false
  gem 'facter', ENV['FACTER_GEM_VERSION'], :require => false
  gem 'puppet', ENV['PUPPET_GEM_VERSION'] || '~> 3.0', :require => false
  gem 'ruby-augeas',                    :require => false
  gem 'nokogiri', '~> 1.6.8',           :require => false
  gem 'rspec-puppet-facts',             :require => false
end

group :development do
  gem 'pry-byebug',                     :require => false
end

# vim:ft=ruby
